version: '2'

services:
  nginx:
    image: 675359748603.dkr.ecr.us-west-2.amazonaws.com/phpcon2017-presentation:nginx
    build:
      context: .
      dockerfile: nginx.dockerfile
    container_name: phpcon2017-ngx
    ports:
      - 80:80
    #mem_limit: "512m"
    volumes_from:
      - php:ro
    links:
      - php

  php:
    image: 675359748603.dkr.ecr.us-west-2.amazonaws.com/phpcon2017-presentation:php
    build:
      context: .
      dockerfile: php.dockerfile
    container_name: phpcon2017-php
    environment:
      SLIM_MODE: "development"
    ports:
      - 9000
    #mem_limit: "512m"
    volumes:
      - ./etc/php-fpm.d/www-development.conf:/usr/local/etc/php-fpm.d/www.conf:ro
      - ./public:/var/www/public
      - ./src:/var/www/src
      - ./templates:/var/www/templates
      - ./vendor:/var/www/vendor
